version: "3.9"
services:

  # postgres db
  db:
    image: postgres:14.5
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./database/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    
  # master spark node
  spark-master:
    build: .
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./exec:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  # spark worker 1
  spark-1:
    build: .
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-1
    volumes:
       - ./exec:/opt/spark-apps
       - ./data:/opt/spark-data

  # spark worker 2
  spark-2:
    build: .
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-2
    volumes:
        - ./exec:/opt/spark-apps
        - ./data:/opt/spark-data

